
const NUM_OF_BIT_BUTTONS = 7;
const MILI_PER_ONE_ROTATION = 4000;
const RAD_PER_BEAT_BOUNCE = 2 * Math.PI / 20;
const Y_PER_BEAT_BOUNCE = 10;

const COLOR_PALETTE = [0xB22222, 0xFF4500, 0xFFD700, 0x7CFC00, 0x4682B4, 0x0000FF, 0x9400D3];

const ACTION_DOWN = 0;
const ACTION_UP = 1;

const STATE_PAUSE = 0;
const STATE_PRE_RECORDING = 1;
const STATE_RECORDING = 2;
const GLOBAL_START_TIME = Date.now();

const WIDTH_OF_BIT_BUTTONS = 70;
const HEIGHT_OF_BIT_BUTTONS = 100;
const X_OF_BIT_BUTTONS = -240;
const Z_OF_BIT_BUTTONS = 750;
const GAP_OF_BIT_BUTTONS = 10;

const CANVAS_SIZE = 900;
const CAMERA_POS_Y = 500;
const CAMERA_POS_Z = 1000;

const OSC_STOP = 0;
const OSC_START = 1;

const NUM_OF_SAMPLES = 44100;

export {
  CANVAS_SIZE,
  CAMERA_POS_Y,
  CAMERA_POS_Z,

  NUM_OF_BIT_BUTTONS, 
  MILI_PER_ONE_ROTATION,
  RAD_PER_BEAT_BOUNCE,
  Y_PER_BEAT_BOUNCE,
  COLOR_PALETTE,
  
  ACTION_DOWN,
  ACTION_UP,
  
  STATE_PAUSE,
  STATE_PRE_RECORDING,
  STATE_RECORDING,

  GLOBAL_START_TIME,

  WIDTH_OF_BIT_BUTTONS,
  HEIGHT_OF_BIT_BUTTONS,
  X_OF_BIT_BUTTONS,
  Z_OF_BIT_BUTTONS,
  GAP_OF_BIT_BUTTONS,

  OSC_STOP,
  OSC_START
}