
const NUM_OF_BIT_BUTTONS = 7;
const NUM_OF_DRUM_BUTTONS = 7;
const MILI_PER_ONE_ROTATION = 4000;
const RAD_PER_BEAT_BOUNCE = 2 * Math.PI / 20;
const Y_PER_BEAT_BOUNCE = 10;

const KEY_COLOR_PALETTE = [0xB22222, 0xFF4500, 0xFFD700, 0x7CFC00, 0x4682B4, 0x0000FF, 0x9400D3];
const DRUM_COLOR_PALETTE = [0xF03C31, 0xEF9D54, 0x2CD7C4, 0xA2D838, 0xFDE306, 0x945CA5, 0xFEFFF1];

const ACTION_DOWN = 0;
const ACTION_UP = 1;

const STATE_PAUSE = 0;
const STATE_PRE_RECORDING = 1;
const STATE_RECORDING = 2;
const GLOBAL_START_TIME = Date.now();

const WIDTH_OF_BIT_BUTTONS = 70;
const HEIGHT_OF_BIT_BUTTONS = 100;
const RADIUS_OF_CIRCLE = 25;
const X_OF_BIT_BUTTONS = -240;
const Z_OF_BIT_BUTTONS = 750;
const GAP_OF_BIT_BUTTONS = 10;
const GAP_OF_DRUM_BUTTONS = 30;
const X1_OF_DRUM_BUTTONS = -140;

const CANVAS_SIZE = 900;
const CAMERA_POS_Y = 500;
const CAMERA_POS_Z = 1000;

const OSC_STOP = 0;
const OSC_START = 1;

const NUM_OF_SAMPLES = 44100;

export {
  CANVAS_SIZE,
  CAMERA_POS_Y,
  CAMERA_POS_Z,

  NUM_OF_DRUM_BUTTONS,
  NUM_OF_BIT_BUTTONS, 
  MILI_PER_ONE_ROTATION,
  RAD_PER_BEAT_BOUNCE,
  Y_PER_BEAT_BOUNCE,
  KEY_COLOR_PALETTE,
  DRUM_COLOR_PALETTE,
  Z_OF_BIT_BUTTONS,

  ACTION_DOWN,
  ACTION_UP,
  
  STATE_PAUSE,
  STATE_PRE_RECORDING,
  STATE_RECORDING,

  GLOBAL_START_TIME,

  WIDTH_OF_BIT_BUTTONS,
  HEIGHT_OF_BIT_BUTTONS,
  RADIUS_OF_CIRCLE,

  X_OF_BIT_BUTTONS,
  GAP_OF_BIT_BUTTONS,

  X1_OF_DRUM_BUTTONS,

  OSC_STOP,
  OSC_START,

  GAP_OF_DRUM_BUTTONS
}